# basic options
title: Magnus Hansson
author: Magnus Hansson
email: hansson.carl.magnus@gmail.com
description: A page about finance, machine learning, economics, maths, coding and other fun stuff.
github_username: HanssonMagnus

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
theme: minima
future: true
