# basic options
title: Magnus´ blog
author: Magnus Hansson
email: hansson.carl.magnus@gmail.com
description: A page about finance/economics, mathematics, coding, machine learning and other interesting subjects.
github_username: HanssonMagnus

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
theme: minima
future: true

# Google Analytics
google_analytics: UA-132782909-1
