# basic options
title: Magnus' blog
author: Magnus Hansson
email: hansson.carl.magnus@gmail.com
description: A blog about machine learning, maths, coding and other fun stuff.
github_username: HanssonMagnus

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
theme: minima
future: true
